config/routes.rb
Rails.application.routes.draw do
 
  # devise_for :users
    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }

    #クエッションのアクションのルーティング
    get 'questions/index' => 'questions#index'
    resources :questions do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]
    end

    #Advertisementsのルーティング
    get 'advertisements/index' => 'advertisements#index'
    get 'advertisements/new' => 'advertisements#new'

    get 'hello/privacy' => 'hello#privacy'
    resources :comments, only: [:destroy]
    get 'rooms/index' => 'rooms#index'
    resources :users, only: [:show, :index]
    resources :rooms, :only => [:create, :show]
    resources :messages, only: [:create]
    resources :relationships, only: [:create, :destroy]
    
    root 'hello#index' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :authenticate_user!
    def index

        if params[:search] == nil
          @questions = Question.all.order(created_at: :desc).page(params[:page]).per(4)
        elsif params[:search] == ''
          @questions = Question.all.order(created_at: :desc).page(params[:page]).per(4)
        else
          #部分検索
          search = params[:search]
          @questions = Question.where("content LIKE ? OR title LIKE ? ","%#{search}%","%#{search}%").order(created_at: :desc).page(params[:page]).per(4)
        end
    end
   
    def show
        @question = Question.find(params[:id])
        @comments = @question.comments
        @comment = Comment.new
    end 
     
    def new
        @question = Question.new
    end

    def create
        question = Question.new(question_params)
        question.user_id = current_user.id
        if question.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
    
    
    def edit
        @question = Question.find(params[:id])
    end
    
    def update
        question = Question.find(params[:id])
        if question.update(question_params)
          redirect_to :action => "show", :id => question.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
      question = Question.find(params[:id])
      question.destroy
      redirect_to action: :index
    end



    private
    def question_params
      params.require(:question).permit(:title, :content)
    end

    

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
　
    　<div class="question-new-title">
        <%= f.label:title, "質問のタイトル：", {class: 'title-label'}  %>
        <%= f.text_field :title, :size => 100, :class => 'title-field'%>
      </div>
    
      <div class="question-new-content">
        <%= f.label :content, "質問の内容", {class: 'content-label'} %>
        <%= f.text_area :content, :size => "50x15", :class => 'content-field'  %>
        
        <%= f.submit "質問する" , :class => 'submit_class_newquestion' %>
      </div>
    
      
    
 <% end %>
    

app/views/questions/index.html.erb
<br>
<br>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<div class="questions-index">
<div class="left">
  <div class="left-search">
  <span class="box-title">質問を検索</span>
   <%= form_tag({controller:"questions",action:"index"}, method: :get) do %>
     <%= text_field_tag :search, '', class: "search-box", placeholder: "Search..." %>
     <label for="search-box"><span class ="search-icon"><i class="fa fa-search fa-fw"></i></span></label>
     <%= submit_tag '検索する' , id:"search-submit"  %>
   <% end %>

   <script>
     document.addEventListener("touchstart", function(){}, true);
   </script>
   <br>
   <p>
   質問のタイトル、内容で検索ができます。
   また、質問者の研究室や、希望の進路から検索ができ、
   自分と似た質問者の質問などを調べることもできます。
   </p>
   
  </div>
  <div class="create-question">
     <span class="box-title">質問を投稿</span>

     <div class="container">
     <%= link_to "質問投稿へ", new_question_path, {class: "btn-box"} %>
     </div>

     <p class="ppc">
     あなたの知りたいことを直接してみよう。
     同じ悩みを持った人や、悩みを解決してきた人たちが、
     答えてくれます。
     </p>
  </div>
</div>
<!-ページネーション->
<div class="right">

  <div class="bootstrap"><%= paginate @questions %></div>
   <% @questions.each do |t| %>
      <div class="questions-card">
        <%= link_to question_path(t.id) do %>
          <div class="questions-container">
            <div class="question">
             <!--ユーザーの名前とトプ画ここから-->
              <div class="questioner">
                  <div class="questioner-image">
                     <% if t.user.image? %>  
                     <%= image_tag t.user.image_url, size: "30x30" %>
                     <% else %>  
                     <%= image_tag  'default.png', size: "30x30" %>
                    <% end %>
                  </div>
                  <div class="questioner-name">
                    <object><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></object>
                  </div>
               </div>
                     <!--ユーザーの名前とトプ画ここまで-->
                  <div class="question-title">
                    <%= t.title.truncate(30) %><br>
                    <%= t.content.truncate(25) %>
                  </div>
                  <div class="count">
                    <div class="comment-count">
                      コメント<%= t.comments.count %>件
                    </div>
                    &nbsp;
                    <div class="liked-count">
                      いいね<%= t.likes.count %>件
                    </div>
                    &nbsp;
                    <br>
                    <div class="questions-time">
                      <%= t.created_at.to_s(:datetime_jp) %>
                    </div>
                  </div>
             </div>
          </div>
        <% end %>
      </div>
    <% end %>
  
  <% if @questions.count ==4 %>
   <div class="bootstrap"><%= paginate @questions %></div>
  <% end %> 
</div>


</div>






app/views/questions/new.html.erb
<%= form_for @question do |f| %>
　
　<div class="question-new-title">
    <%= f.label:title, "質問のタイトル：", {class: 'title-label'}  %>
    <%= f.text_field :title, :size => 100, :class => 'title-field'%>
  </div>

  <div class="question-new-content">
    <%= f.label :content, "質問の内容", {class: 'content-label'} %>
    <%= f.text_area :content, :size => "50x15", :class => 'content-field'  %>
    
    <%= f.submit "質問する" , :class => 'submit_class_newquestion' %>
  </div>

  

<% end %>

app/views/questions/show.html.erb


<div id="question-show-title">
  <p class="ptitle"><%= @question.title %></p>
  <p class="pquestioner-name"><%= @question.user.name %></p>
</div>

<div id="question-show-content">
  <p class="pcontent"><%= @question.content %></p>
  
  <div class="question-show-bottom">
        
  <div class="question-show-like">
    <% if current_user.already_liked?(@question) %>
        <%= link_to question_like_path(@question), method: :delete do %>
          <p><i class="fas fa-heart"></i></p>
        <% end %>
    <% else %>
        <%= link_to question_likes_path(@question), method: :post do %>
          <p><i class="far fa-heart"></i></p>
        <% end %>
    <% end %>
 </div>
  <div class="ptime">
  <p class="ptime"><%= @question.created_at.to_s(:datetime_jp) %></p>
  </div>
  &nbsp;&nbsp;&nbsp;  
  <div class="change-and-delete">  
  <% if user_signed_in? && current_user.id == @question.user.id %>
    <%= link_to "編集する", edit_question_path(@question.id) %>&nbsp;
    <%= link_to "削除する", question_path(@question.id), method: :delete, data: {confirm: "削除しますか？"} %>  
  <% end %>
  </div>
 </div>
</div>


<div class="comment-wrapper">
  <p class="comment-upper">コメント一覧
     <i class="fas fa-comments"></i>
  </p>
  <% @comments.each do |c| %>
    <div class="balloon">
     
      <div class="comment-content">
        <% if user_signed_in? && current_user.id == c.user.id %>
          <div class="comment-delete">
            <%= link_to(comment_path(c.id), method: :delete, data: {confirm: "削除しますか？"}) do %>
              <i class="fas fa-window-close"></i>
            <% end %>
          </div>
        <% end %>
        <%= c.content %>
      </div>
      
      <div class="comment-user-and-time">
      <div class="comment-user">
        <div class="comment-user-image">
          <% if c.user.image? %>  
            <%= image_tag c.user.image_url, size: "40x40" %>
          <% else %>  
            <%= image_tag  'default.png', size: "40x40" %>
          <% end %>
        </div>
        <div class="comment-user-name">
          <a href="/users/<%= c.user.id %>"><%= c.user.name %></a>
        </div>  
      </div>
      <br>
      <div class="comment-time"><%= c.created_at.to_s(:datetime_jp) %></div>
      </div>
    </div>
      <br>
  <% end %>
   
  <% if user_signed_in? %>
    <%= form_with(model: [@question, @comment], local: true) do |f| %>
      <%= f.text_area :content, class:'text_area' %><br>
      <%= button_tag type: "submit" , class: "btn-box" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>




 