config/routes.rb
Rails.application.routes.draw do
 
  # devise_for :users
    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }

    #クエッションのアクションのルーティング
    get 'questions/index' => 'questions#index'
    resources :questions do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]
    end

    #Advertisementsのルーティング
    get 'advertisements/index' => 'advertisements#index'
    get 'advertisements/new' => 'advertisements#new'

    get 'hello/privacy' => 'hello#privacy'
    resources :comments, only: [:destroy]
    get 'rooms/index' => 'rooms#index'
    resources :users, only: [:show, :index]
    resources :rooms, :only => [:create, :show]
    resources :messages, only: [:create]
    resources :relationships, only: [:create, :destroy]
    
    root 'hello#index' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
  end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :users, through: :entries, source: :user #entryのユーザーIDのuser
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        

        validates_uniqueness_of :memberId
        validates_presence_of :memberId
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 400 } #追記
          
        #memberIdを利用してログインするようにオーバーライド
        def self.find_first_by_auth_conditions(warden_conditions)
            conditions = warden_conditions.dup
            if login = conditions.delete(:login)
        #認証の条件式を変更する
               where(conditions).where(["memberId = :value", { :value => memberId }]).first
            else
               where(conditions).first
            end
        end
        
        def email_required?
          false
        end
      
        def email_changed?
          false
        end

        mount_uploader :image, ImageUploader

        has_many :questions, dependent: :destroy
        has_many :comments, dependent: :destroy
        has_many :messages, dependent: :destroy
        has_many :entries, dependent: :destroy
        has_many :rooms, through: :entries, source: :room
        has_many :likes, dependent: :destroy
        has_many :liked_questions, through: :likes, source: :question
        
        #relationship
        #foregin_key = 入口 
        #source = 出口

        has_many :relationships 
        has_many :followings, through: :relationships, source: :follow #「relationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセスしてね」
        has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id' 
        has_many :followers, through: :reverse_of_relationships, source: :user

        def follow(other_user) #followingの時点でもうクリエイトしてるのに（クリエイトはセーブを含むから）次の行のセーブはいるのか？
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end


        def already_liked?(question)
          self.likes.exists?(question_id: question.id)
        end

      
      
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    
    
    def index

    end

    def privacy
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
      def create
        like = current_user.likes.create(question_id: params[:question_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(question_id: params[:question_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @user = User.find(current_user.id) #userはログインしている人
    @rooms = @user.rooms #ログインしている人のルーム一覧

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

    def index
        
        if params[:search] == nil
            @users = User.all.page(params[:page]).per(4)
          elsif params[:search] == ''
            @users = User.all.page(params[:page]).per(4)
          else
            #部分検索
            search = params[:search]
            @users = User.where("name LIKE ? OR labo LIKE ? OR course LIKE ? ","%#{search}%", "%#{search}%", "%#{search}%").page(params[:page]).per(4)
          end
    end

    def show
        @user = User.find(params[:id]) 
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
        @questions =@user.questions.page(params[:page]).per(4)
        if @user.id == current_user.id
        else
          @currentUserEntry.each do |cu|
            @userEntry.each do |u|
              if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
              end
            end
          end
          if @isRoom
          else
            @room = Room.new
            @entry = Entry.new
          end
        end
     end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<div class ="rooms-index">
<% if current_user.id == @user.id %>
  <h3 class ="room-title">DM一覧</h3>
  <% @rooms.each do |r| %>
    <% r.users.each do |u| %> <!--ルームのユーザーは二人-->
     <% if u.id == current_user.id %> <!--自分じゃない方は表示-->
     <% else %>
     
      <div class="rooms-card">
        <%= link_to room_path(r.id) do %>
          <div class="rooms-container">
            <div class="room">
             <!--ユーザーの名前とトプ画ここから-->
              <div class="talker">
                  <div class="talker-image">
                     <% if u.image? %>  
                     <%= image_tag u.image_url, size: "30x30" %>
                     <% else %>  
                     <%= image_tag  'default.png', size: "30x30" %>
                    <% end %>
                  </div>
                  <div class="talker-name">
                    <object><a href="/users/<%= u.id %>"><%= u.name %></a></object>
                  </div>
               </div>
                     <!--ユーザーの名前とトプ画ここまで-->
                  <div class="last-talk">
                  <% if Message.find_by(id: r.message_ids.last) %> 
                    <div class="last-talk-content"><%= Message.find_by(id: r.message_ids.last).content.truncate(30) %></div>
                    <div class="last-talk-time"><%= Message.find_by(id: r.message_ids.last).created_at.to_s(:datetime_jp) %></div>
                  <% end %>  
                  </div>
             </div>
          </div>
        <% end %>
      </div>
     <% end %>
    <% end %> 
    <% end %>
<% else %>
<% end %>
</div>
<br>
<br>




app/views/rooms/show.html.erb
<div class="talkbody">

<% @entries.each do |e| %>
  <% if e.user.id == current_user.id %>
  <% else %>
  <div class="others"><%= e.user.name %>とのトーク</div>
  <% end %>
<% end %>


<% if @messages.present? %>
  <% @messages.each do |m| %>
      <% if m.user.id == current_user.id %>
      <div class="balloon_r">
        <div class="faceicon">
          <% if m.user.image? %>  
            <%= image_tag m.user.image_url, size: "30x30" %>
          <% else %>  
            <%= image_tag  'default.png', size: "30x30" %>
          <% end %>
        </div>
        <div class="says">
        <div class="message-content"><p><%= m.content %></p></div>
        <br>
          <div><small class="message-time"><%= m.created_at.to_s(:datetime_jp) %></small></div>
        </div>
      </div>
      <% else %>
      <div class="balloon_l">
        <div class="faceicon">
          <% if m.user.image? %>  
            <%= image_tag m.user.image_url, size: "30x30" %>
          <% else %>  
            <%= image_tag  'default.png', size: "30x30" %>
          <% end %>
        </div>
        <div class="says">
          <div class="message-content"><p><%= m.content %></p></div>
        <br>
          <div><small class="message-time"><%= m.created_at.to_s(:datetime_jp) %></small></div>
        </div>
      </div>
      <% end %>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>


  
   
  

<div class="messageForm">
<%= form_for @message do |f| %>
  <%= f.text_area :content, :placeholder => "メッセージを入力して下さい" , class:"text_area" %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= button_tag type: "submit" , class: "btn-box" do %>
    <i class="far fa-comments"></i> 送信する
  <% end %>
<% end %>
</div>


</div>