config/routes.rb
Rails.application.routes.draw do
 
  # devise_for :users
    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }

    #クエッションのアクションのルーティング
    get 'questions/index' => 'questions#index'
    resources :questions do
      resources :comments, only: [:create]
      resources :likes, only: [:create, :destroy]
    end

    #Advertisementsのルーティング
    get 'advertisements/index' => 'advertisements#index'
    get 'advertisements/new' => 'advertisements#new'

    get 'hello/privacy' => 'hello#privacy'
    resources :comments, only: [:destroy]
    get 'rooms/index' => 'rooms#index'
    resources :users, only: [:show, :index]
    resources :rooms, :only => [:create, :show]
    resources :messages, only: [:create]
    resources :relationships, only: [:create, :destroy]
    
    root 'hello#index' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates_uniqueness_of :question_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
  end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
    has_many :users, through: :entries, source: :user #entryのユーザーIDのuser
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        

        validates_uniqueness_of :memberId
        validates_presence_of :memberId
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 400 } #追記
          
        #memberIdを利用してログインするようにオーバーライド
        def self.find_first_by_auth_conditions(warden_conditions)
            conditions = warden_conditions.dup
            if login = conditions.delete(:login)
        #認証の条件式を変更する
               where(conditions).where(["memberId = :value", { :value => memberId }]).first
            else
               where(conditions).first
            end
        end
        
        def email_required?
          false
        end
      
        def email_changed?
          false
        end

        mount_uploader :image, ImageUploader

        has_many :questions, dependent: :destroy
        has_many :comments, dependent: :destroy
        has_many :messages, dependent: :destroy
        has_many :entries, dependent: :destroy
        has_many :rooms, through: :entries, source: :room
        has_many :likes, dependent: :destroy
        has_many :liked_questions, through: :likes, source: :question
        
        #relationship
        #foregin_key = 入口 
        #source = 出口

        has_many :relationships 
        has_many :followings, through: :relationships, source: :follow #「relationshipsテーブルのfollow_idを参考にして、followingsモデルにアクセスしてね」
        has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id' 
        has_many :followers, through: :reverse_of_relationships, source: :user

        def follow(other_user) #followingの時点でもうクリエイトしてるのに（クリエイトはセーブを含むから）次の行のセーブはいるのか？
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end


        def already_liked?(question)
          self.likes.exists?(question_id: question.id)
        end

      
      
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    
    
    def index

    end

    def privacy
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
      def create
        like = current_user.likes.create(question_id: params[:question_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(question_id: params[:question_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITL Experience Commons</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>

<div class="menu">
 <h1><%= link_to "iTL Experience commons", root_path %></h1>
 <div class="menu-list">
 <ul>           
 <% if user_signed_in? %>
 <li><%= link_to "マイページ", user_path(current_user.id) %></li>

 <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
 <div class="overlay" id="js-overlay"></div>
    <div class="hamburger" id="js-hamburger">
      <span class="hamburger__lineTop"></span>
      <span class="hamburger__lineCenter"></span>
      <span class="hamburger__lineBottom"></span>
    </div>
 <% else %>
 <li><%= link_to "ログイン", questions_path %></li>

 <li><%= link_to "新規登録", new_user_registration_path %></li>
 <div class="overlay" id="js-overlay"></div>
    <div class="hamburger" id="js-hamburger">
      <span class="hamburger__lineTop"></span>
      <span class="hamburger__lineCenter"></span>
      <span class="hamburger__lineBottom"></span>
    </div>
 <% end %>
 </ul>
 </div>
</div>

<div class="sideMenu">
  <nav>
    <ul>
        <% if user_signed_in? %>
        <li><%= link_to "質問一覧", questions_path %></li>
        <li><%= link_to "ユーザー一覧", users_path %></li> 
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "DM一覧", rooms_index_path %></li>

        <% else %>
        <li><%= link_to "ログイン", questions_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
　　　　 <% end %>
    </ul>
  </nav>
</div>

  </header>
  <main>
    <%= yield %>
  </main>

  <footer>
  <p>Copyright © Kuzuoka Takuma All Rights Reserved.</p>
 </footer>

<script>
  function toggleNav() {
    const body = document.body;
    const hamburger = document.getElementById("js-hamburger");
    const overlay = document.getElementById("js-overlay");
    hamburger.addEventListener("click", function () {
      body.classList.toggle("nav-open");
    });
    overlay.addEventListener("click", function () {
      body.classList.remove("nav-open");
    });
  }
  toggleNav();
</script>

  </body>
  </html>
  